### ISSUE TITLE
Fast swiping through images does not work

### ISSUE THREAD

**Issue by guettli** [k3b/AndroFotoFinder#10]
If you swipe through images fast, the swiping gets ignored often.

Only slow swiping seems to work.

My device: Samsung Tablet SM-T800

**Comment by guettli** [comment]
How fast you can swipe seems to related to the image size.

Big pictures from my Canon 40D (jpg) can't be swiped fast. But small images from my mobile phone can be swiped fast.

**Comment by k3b** [comment]
In current implementation swiping pauses until loading the next image into memory has finished. The bigger the image the more time is needed :-( . I have only small images on my tablet so i was not aware of the problem.

I am not shure if i can fix this  ...

**Comment by k3b** [comment]
I made swiping faster by initially loading a low res image. on first zoom it is reloaded with maximum resolution.

will be available in v0.4.2

**Comment by guettli** [comment]
Thank you for the fast response.
