### ISSUE TITLE
Select Path: Show folder/images count in gray

### ISSUE THREAD

**Issue by guettli** [k3b/AndroFotoFinder#11]
The select path dialog looks confusing. 

I though about it and have not found a very good solution yet.

One thing that could be improved: Make the directory name bold,
or show the folder and image counts in gray.

Background: My folder names are numbers (YYYY/MM/DD).

It would be more easy to read the dialog if you can see the folder names immediately.

But I would display the subfolder count. But maybe right aligned. Keeping space between the directory name and the numbers ...

BTW: thank you for this nice app :-)

**Comment by k3b** [comment]
done: In the List  the folder name now is in bold and the counts remain in non-bold. 

I donot know how to do it in the  buttons of the path bar.

Should be available in version 0.4.2 in october

**Comment by guettli** [comment]
Thank you!
