### ISSUE TITLE
Message: "Not enough memory, showing reduced preview instead"

### ISSUE THREAD

**Issue by guettli** [k3b/AndroFotoFinder#15]
I get the message

```
Not enough memory, showing reduced preview instead
```

What kind of memory is not enough?

My internal and external SD card have enough.

RAM seems to be enough, too.

Is there anything a user can do?

**Comment by k3b** [comment]
android can handle only 4096*4096 pixels (about 65 Megabyte) per non-copressed image. I already improved scaling of big images in v0.4.2 by downsizig image to 4096*4096 pixels so it should work better if the device has enought free ram.

**Comment by guettli** [comment]
Why not downsize the image to the fullscreen resolution to of the device. I guess this is less then 4096*4096 in most cases. This means you need less memory. I wrote an image program with pyhton-gtk some years ago. You could specify the size during loading the image. I guess this could be done with java, too.

**Comment by k3b** [comment]
> downsize the image to the fullscreen resolution to of the device
that is what i did for fast swiping

If you start zooming the zoom-lib requires more resolution

**Comment by k3b** [comment]
with new 0.4.2. this should not happen any more
