### ISSUE TITLE
Ability to erase(/edit) pic

### ISSUE THREAD

**Issue by MaxLanar** [k3b/AndroFotoFinder#2]
Hello,
I hope it is the right place to ask this.

It would be nice to have the possibility to erase pictures while viewing them (like in the gallery app). And with the possibility to edit them (again like in the gallery app) it would be awesome ! :)

Hope you (/someone) can add this. :)

Thanks for your great program (it was really something that was missing on Android)  !

(Sorry for my bad english)

**Comment by k3b** [comment]
.. is currently under develeopment.

yesterday-s v0.4.0 release already contains "delete"

**Comment by k3b** [comment]
will be available in 0.4.1

**Comment by MaxLanar** [comment]
You rock !
