### ISSUE TITLE
Write GPS EXIF from Android geotags

### ISSUE THREAD

**Issue by bulldozer2003** [k3b/AndroFotoFinder#31]
I found today that the stock camera app does not write GPS locations to the EXIF data in the jpeg files themselves. The gallery app, and this app, however, can show the exact location where the photo was taken. Does Android keep a separate database of geotagged locations?

Using this app I was able to write proper GPS EXIF tags to a couple of photos, but I'd really like to be able to do so to every picture in a batch. Is it possible for this feature to be added?

**Comment by k3b** [comment]
i donot know of any external media-file/database where gps of taken photos are stored to. 
my stock camera app has an option to enable/disable "gps in exif". the free android apps OpenCamera and GoogleCamera also support exif-gps info.

androFotoFinder does not support "batch-set geo" but you can 

* set the filter "[x] no geo" to see only non-gps-photos. 
* with multiselection  you can select all photos form one geo-posion and assingn them together the gps with one step.

The next version will also support #30 gps bookmark support to store and retrieve frequently uses geo-positions
