### ISSUE TITLE
Why not installable via google play?

### ISSUE THREAD

**Issue by guettli** [k3b/AndroFotoFinder#8]
Please make the app installable via google play.

If you have good reasons to not do it, then please tell us the reason here:
 
https://github.com/k3b/AndroFotoFinder

Thank you.

**Comment by k3b** [comment]
i have good reasons and i do not want to make the reasons public

**Comment by guettli** [comment]
I am curious. The app is good. If you don't want to make it public you can write me a private mail: info.fotofinder@thomas-guettler.de

**Comment by abitrolly** [comment]
Most people prefer convenience over privacy, and sometimes it is not a motivation to build privacy protecting tools. Just my 0.02 cents.
