### ISSUE TITLE
Open Foto Finder via "My Files" (Samsung) App

### ISSUE THREAD

**Issue by guettli** [k3b/AndroFotoFinder#9]
It would be nice if you could open foto finder via "My Files" app (Samsung).

If I push on a image in MyFiles (folder view), then I can open the image with gallery or fotos (both the google default apps).

I have no clue how to implement it.

**Comment by k3b** [comment]
This is a duplicate of #3 implemented in version v0.4.1 which is should be available in fdroid on 2015-09-13
